LessonPlan.Web/Models/ErrorViewModel.cs
namespace LessonPlan.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LessonPlan.Web/Controllers/HomeController.cs
using LessonPlan.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LessonPlan.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LessonPlan.Web/Controllers/TeachersController.cs
using LessonPlan.Core.Dtos;
using LessonPlan.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LessonPlan.Web.Controllers
{
    public class TeachersController : Controller
    {
        private readonly TeacherApiService _teacherApiService;

        public TeachersController(TeacherApiService teacherApiService)
        {
            _teacherApiService = teacherApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _teacherApiService.GetAllAsync());
        }

        public async Task<IActionResult> Save()
        {
            var teachersDto = await _teacherApiService.GetAllAsync();

            ViewBag.categories = new SelectList(teachersDto, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(TeacherDto teacherDto)
        {
            if (ModelState.IsValid)
            {
                await _teacherApiService.SaveAsync(teacherDto);

                return RedirectToAction(nameof(Index));
            }

            var teachersDto = await _teacherApiService.GetAllAsync();

            ViewBag.categories = new SelectList(teachersDto, "Id", "Name");

            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var teacher = await _teacherApiService.GetByIdAsync(id);

            return View(teacher);
        }

        [HttpPost]
        public async Task<IActionResult> Update(TeacherDto teacherDto)
        {
            if (ModelState.IsValid)
            {
                await _teacherApiService.UpdateAsync(teacherDto);

                return RedirectToAction(nameof(Index));
            }

            var teachersDto = await _teacherApiService.GetAllAsync();

            ViewBag.categories = new SelectList(teachersDto, "Id", "Name", teacherDto.Id);

            return View(teacherDto);
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _teacherApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LessonPlan.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LessonPlan.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LessonPlan.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LessonPlan.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LessonPlan.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teachers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LessonPlan.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LessonPlan.Web/Views/Teachers/Index.cshtml
@using LessonPlan.Core.Dtos;

@{
    ViewData["Title"] = "Index";
}

@model List<TeacherDto>
<a class="btn btn-primary" asp-controller="Teachers" asp-action="Save">Save Teacher</a>
<table class="table table-striped">
    <thead>
        <tr>
            <td>Id</td>
            <td>Teacher Name</td>
            <td>Classroom</td>
            <td>Lesson</td>
            <td>Lesson Time</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.TeacherName</td>
                <td>@item.ClassRoomId</td>
                <td>@item.LessonId</td>
                <td>@item.LessonTimeId</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Teachers" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-controller="Teachers" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

LessonPlan.Web/Views/Teachers/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model TeacherDto
<h1>Save Teacher</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="Teachers">
            <div class="form-group">
                <label asp-for="TeacherName"></label>
                <input asp-for="TeacherName" class="form-control" />
                <span asp-validation-for="TeacherName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ClassRoomId"></label>
                <input asp-for="ClassRoomId" class="form-control" />
                <span asp-validation-for="ClassRoomId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LessonId"></label>
                <input asp-for="LessonId" class="form-control" />
                <span asp-validation-for="LessonId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LessonTimeId"></label>
                <input asp-for="LessonTimeId" class="form-control" />
                <span asp-validation-for="LessonTimeId" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Save" class="btn-primary" />

            </div>
        </form>



    </div>


</div>

LessonPlan.Web/Views/Teachers/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model TeacherDto
<h1>Update Teacher</h1>

<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="Teachers">
            <input type="hidden" asp-for="Id" />
           
           <div class="form-group">
                <label asp-for="TeacherName"></label>
                <input asp-for="TeacherName" class="form-control" />
                <span asp-validation-for="TeacherName" class="text-danger"></span>
            </div>     

           <div class="form-group">
                <label asp-for="ClassRoomId"></label>
                <input asp-for="ClassRoomId" class="form-control" />
                <span asp-validation-for="ClassRoomId" class="text-danger"></span>
            </div>
            
           <div class="form-group">
                <label asp-for="LessonId"></label>
                <input asp-for="LessonId" class="form-control" />
                <span asp-validation-for="LessonId" class="text-danger"></span>
            </div>

           <div class="form-group">
                <label asp-for="LessonTimeId"></label>
                <input asp-for="LessonTimeId" class="form-control" />
                <span asp-validation-for="LessonTimeId" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="submit" value="Update" class="btn-primary" />

            </div>
        </form>



    </div>


</div>